name: Test Workflow
on: 
  pull_request:
    branches:
      - trunk
jobs:
  build:
    name: Build release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        id: build
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'woocommerce.zip'